name: AJ
favicon: null
layout_spectrum: 0.5690828633960336
typography_spectrum: 0.668693397892639
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5635746214538813
  lightness: 0.31708599580451846
  saturation: 0.06484431051649153
  rhythmicContrast: 0.05498853442259133
purpose: []
