name: Grid
favicon: null
layout_spectrum: 0.50436
typography_spectrum: 0.31875
title: Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffd300'
    - '#ffffff'
    - '#b4b4b4'
    - '#000000'
    - '#454545'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
